addSbtPlugin("io.spray"       % "sbt-revolver"        % "0.10.0")
addSbtPlugin("ch.epfl.scala"  % "sbt-scalafix"        % "0.13.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"        % "2.5.1")
addSbtPlugin("com.github.sbt" % "sbt-native-packager" % "1.9.16")
addSbtPlugin("dev.zio"        % "zio-sbt-ecosystem"   % "0.4.0-alpha.28")
